version: "3.9"
services:
  my_postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "my_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    networks:
      - data
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - my_postgres
    restart: always
    volumes:
      - ./stocks_products:/app
    env_file:
      - ./config/_env
    networks:
      - data
      - back
    expose:
     - 8080

  nginx:
    image: nginx:latest
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./config/default.conf:/etc/nginx/conf.d/default.conf
      - ./stocks_products:/app
    depends_on:
      - backend
    networks:
      - back
    ports:
      - 80:80

networks:
  data:
  back:
